baseURL: https://blog.faarao.net
disablePathToLower: true
languageCode: en-gb
title: The Rambling Priest
authors:
  ellen:
    name: Ellen Rönnholm
    twitter: eilyra

permalinks:
  post: /:year/:month/:day/:slug/

blackfriday:
  extension:
    - footnotes