baseURL: https://blog.faarao.net
disablePathToLower: true
languageCode: en-gb
title: The Rambling Priest
authors:
  ellen:
    name: Ellen Rönnholm
    twitter: eilyra

permalinks:
  post: /:year/:month/:day/:filename/

blackfriday:
  extension:
    - footnotes

params:
  about: "Sometimes I decide I want to write something, those things end up here. Mostly focused on my adventures in World of Warcraft at the moment."