[context.production]
    command = "hugo"
    publish = "public"

[[redirects]]
    from = "/xmlrpc.php"
    to = "https://laatikot.faarao.net/xmlrpc.php"
    status = 200
    headers = {Host = "blog.faarao.net"}
