backend:
  name: git-gateway
  branch: master

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "post"
    label: "Post"
    folder: "content/post"
    create: true
    slug: "{{year}}/{{slug}}"
    fields:
      - {label: "Categories", name: "categories", widget: "list", default: ["World of Warcraft"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string", default: "ellen"}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ"}